version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies...
      - npm install -g serverless
      - npm install

  build:
    commands:
      - echo Deploying using Serverless Framework...
      - npm run build:webpack
      - sls deploy --stage production

artifacts:
  files:
    - '**/*'
