service: serverless-nestjs
useDotenv: true

plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs22.x
  stage: ${env:ENV}
  region: ap-south-1

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

  esbuild: false
