service: serverless-nestjs
useDotenv: true

plugins:
  - serverless-offline

provider: aws
runtime: nodejs20.x

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
